stages:
  - test-triggers
  - release-trigger

frontend_pipeline:
  stage: test-triggers
  trigger:
    include:
      - local: booklore-ui/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - booklore-ui/**/*
    - when: never

backend_pipeline:
  stage: test-triggers
  trigger:
    include:
      - local: booklore-api/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - booklore-api/**/*
    - when: never

releases_pipeline:
  stage: release-trigger
  trigger:
    include:
      - local: .gitlab/ci/releases.yml
    strategy: depend
  needs:
    - job: frontend_pipeline
    - job: backend_pipeline
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - .gitlab-ci.yml
        - .gitlab/**/*
        - Dockerfile
        - Dockerfile.*
        - docker/**/*
        - compose/**/*
        - scripts/**/*
        - docs/**/*
        - .editorconfig
        - .gitignore
        - README*
        - LICENSE*
        - gradle/**/*
        - package*.json
        - yarn.lock
        - pnpm-lock.yaml

    - when: never
