name: Publish Release Image

on:
  release:
    types:
      - "published"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set Up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: booklore-ui/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./booklore-ui
        run: npm ci

      - name: Build Angular App
        working-directory: ./booklore-ui
        run: npx ng build --configuration=production

      - name: Upload Booklore Frontend Application
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: booklore-ui
          path: booklore-ui/dist/booklore/browser/


  build-backend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Download Angular Dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: booklore-ui
          path: booklore-ui/dist/booklore/browser/

      - name: Set Up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Copy Angular Dist to Spring Boot Resources
        run: cp -r booklore-ui/dist/booklore/browser/. booklore-api/src/main/resources/static/

      - name: Inject Version into application.yaml
        env:
          APP_VERSION: ${{github.event.release.tag_name}}
        run: |
          APP_VERSION=${APP_VERSION#v}

          sed -i "s/version: \"development\"/version: \"$APP_VERSION\"/" \
            booklore-api/src/main/resources/application.yaml

      - name: Build Spring Boot JAR
        env:
          APP_VERSION: ${{github.event.release.tag_name}}
        working-directory: ./booklore-api
        run: |
          APP_VERSION=${APP_VERSION#v}

          ./gradlew \
            build \
            --exclude-task test \
            --no-daemon \
            --parallel \
            --build-cache \
            --project-prop version="$APP_VERSION"

      - name: Upload Booklore Backend Application
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: booklore-api
          path: booklore-api/build/libs/

  ghcr-publish:
    needs: build-backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Download Spring Boot jar
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: booklore-api
          path: booklore-api/build/libs/

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set Up QEMU for Multi-Architecture Builds
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: Dockerfile.ci
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  attach-to-release:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Download Spring Boot jar
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: booklore-api
          path: booklore-api/build/libs/

      - name: Upload to Release
        env:
          APP_VERSION: ${{github.event.release.tag_name}}
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          cd booklore-api/build/libs/
          gh release upload "$APP_VERSION" *.jar       
        shell: bash
